# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 263cdb339aeacea015cf1d9fe6822e29584d87cb09b8c9f4a6a849ae7bf140b32afbfcd9d2032fa964e7ed6394e668ff5df5fb95800b06b4a882461e3e00ac11

test:
  secret_key_base: 57fa9a174d921b1055432ab010a557ed933dce17f03253632544e28ed87f7506259b0a9cb7aa49d092b9e2b02c4fe6b172228613adbf4ab331c4ed22ab361a6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
